repos:
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.0
    hooks:
      - id: poetry-check
        args: ["-C", "./cdk"]
      - id: poetry-lock
        args: ["-C", "./cdk"]
      - id: poetry-export
        args:
          [
            "-C",
            "./cdk",
            "-f",
            "requirements.txt",
            "-o",
            "./cdk/requirements.txt",
          ]
      - id: poetry-install
        args: ["-C", "./cdk"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        additional_dependencies: [flake8-pyproject]
        args: [--toml-config=cdk/pyproject.toml]
        files: ^cdk/
