[tool.poetry]
name = "cdk"
version = "0.1.0"
description = ""
authors = ["Anton Jackson-Smith <anton@bnext.bio>"]
readme = "README.md"
homepage = "https://nucleus.bnext.bio/"
repository = "https://github.com/bnext-bio/bnext/"
packages = [
    { include = "cdk", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^2.1.2"
pandas = "^2.2.3"
seaborn = "^0.13.2"
matplotlib = "^3.9.2"
tqdm = "^4.66.5"
rich = "^13.9.2"
openpyxl = "^3.1.5"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
flake8 = "^7.1.1"
black = "^24.10.0"
pre-commit = "^4.0.0"

[tool.black]
line-length = 120
target-version = ['py311']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra"
testpaths = [
    "tests",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

